name: 'Godot GUT CI'
description: 'Run Godot GUT tests on CI'
branding:
  icon: alert-triangle
  color: gray-dark
inputs:
  godot_version:
    description: 'Godot Version'
    required: false
    default: '3.5.1'
  gut_params:
    description: 'GUT parameters (https://github.com/bitwes/Gut/wiki/Command-Line)'
    required: false
    default: -gdir=res://tests
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.godot_version }}
    - ${{ inputs.gut_params }}
